### Project - MovieLens Data Analysis

The GroupLens Research Project is a research group in the Department of Computer Science and Engineering at the University of Minnesota. The data is widely used for collaborative filtering and other filtering solutions. However, we will be using this data to act as a means to demonstrate our skill in using Python to “play” with data.

#### Domain 
Internet and Entertainment

**Note that the project will need you to apply the concepts of groupby and merging extensively.**

#### 1. Import the necessary packages - 2.5 marks

In [9]:
import pandas as pd

#### 2. Read the 3 datasets into dataframes - 2.5 marks

In [22]:
df_data = pd.read_csv('https://raw.githubusercontent.com/aaroncfo/AIML/master/Data.csv')
df_item = pd.read_csv('https://raw.githubusercontent.com/aaroncfo/AIML/master/item.csv')
df_user = pd.read_csv('https://raw.githubusercontent.com/aaroncfo/AIML/master/user.csv')

#### 3. Apply info, shape, describe, and find the number of missing values in the data - 5 marks

##### 3a Movie Dataset

In [23]:
# check the profile of the data
print(df_data.info());

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 4 columns):
user id      100000 non-null int64
movie id     100000 non-null int64
rating       100000 non-null int64
timestamp    100000 non-null int64
dtypes: int64(4)
memory usage: 3.1 MB
None


In [26]:
# check the shape of the data
print(df_data.shape)

(100000, 4)


There are 100000 rows and 4 columns in the movie dataset

In [27]:
# describe the data
print(df_data.describe())

            user id       movie id         rating     timestamp
count  100000.00000  100000.000000  100000.000000  1.000000e+05
mean      462.48475     425.530130       3.529860  8.835289e+08
std       266.61442     330.798356       1.125674  5.343856e+06
min         1.00000       1.000000       1.000000  8.747247e+08
25%       254.00000     175.000000       3.000000  8.794487e+08
50%       447.00000     322.000000       4.000000  8.828269e+08
75%       682.00000     631.000000       4.000000  8.882600e+08
max       943.00000    1682.000000       5.000000  8.932866e+08


In [28]:
# check for missing data
def missing_check(df):
    total = df.isnull().sum().sort_values(ascending=False)   # total number of null values
    percent = (df.isnull().sum()/df.isnull().count()).sort_values(ascending=False)  # percentage of values that are null
    missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])  # putting the above two together
    return missing_data # return the dataframe
missing_check(df_data)

Total  Percent
timestamp      0      0.0
rating         0      0.0
movie id       0      0.0
user id        0      0.0

The movie dataset has no missing values

#### 3b Item Dataset


In [30]:
# check the profile of the data
print(df_item.info());

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1681 entries, 0 to 1680
Data columns (total 22 columns):
movie id        1681 non-null int64
movie title     1681 non-null object
release date    1681 non-null object
unknown         1681 non-null int64
Action          1681 non-null int64
Adventure       1681 non-null int64
Animation       1681 non-null int64
Childrens       1681 non-null int64
Comedy          1681 non-null int64
Crime           1681 non-null int64
Documentary     1681 non-null int64
Drama           1681 non-null int64
Fantasy         1681 non-null int64
Film-Noir       1681 non-null int64
Horror          1681 non-null int64
Musical         1681 non-null int64
Mystery         1681 non-null int64
Romance         1681 non-null int64
Sci-Fi          1681 non-null int64
Thriller        1681 non-null int64
War             1681 non-null int64
Western         1681 non-null int64
dtypes: int64(20), object(2)
memory usage: 289.0+ KB
None


In [31]:
# check the shape of the data
print(df_item.shape)

(1681, 22)


The dataset has 1681 rows and 22 columns

In [32]:
# describe the data
print(df_item.describe())

          movie id      unknown       Action    Adventure    Animation  \
count  1681.000000  1681.000000  1681.000000  1681.000000  1681.000000   
mean    841.841761     0.000595     0.149316     0.080309     0.024985   
std     485.638077     0.024390     0.356506     0.271852     0.156126   
min       1.000000     0.000000     0.000000     0.000000     0.000000   
25%     422.000000     0.000000     0.000000     0.000000     0.000000   
50%     842.000000     0.000000     0.000000     0.000000     0.000000   
75%    1262.000000     0.000000     0.000000     0.000000     0.000000   
max    1682.000000     1.000000     1.000000     1.000000     1.000000   

         Childrens       Comedy        Crime  Documentary        Drama  \
count  1681.000000  1681.000000  1681.000000  1681.000000  1681.000000   
mean      0.072576     0.300416     0.064842     0.029744     0.431291   
std       0.259516     0.458576     0.246321     0.169931     0.495404   
min       0.000000     0.000000     0

In [33]:
# check for missing data
def missing_check(df):
    total = df.isnull().sum().sort_values(ascending=False)   # total number of null values
    percent = (df.isnull().sum()/df.isnull().count()).sort_values(ascending=False)  # percentage of values that are null
    missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])  # putting the above two together
    return missing_data # return the dataframe
missing_check(df_item)

Total  Percent
Western           0      0.0
War               0      0.0
movie title       0      0.0
release date      0      0.0
unknown           0      0.0
Action            0      0.0
Adventure         0      0.0
Animation         0      0.0
Childrens         0      0.0
Comedy            0      0.0
Crime             0      0.0
Documentary       0      0.0
Drama             0      0.0
Fantasy           0      0.0
Film-Noir         0      0.0
Horror            0      0.0
Musical           0      0.0
Mystery           0      0.0
Romance           0      0.0
Sci-Fi            0      0.0
Thriller          0      0.0
movie id          0      0.0

The dataset has no missing values

#### 3c User Dataset

In [34]:
# check the profile of the data
print(df_user.info());

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
user id       943 non-null int64
age           943 non-null int64
gender        943 non-null object
occupation    943 non-null object
zip code      943 non-null object
dtypes: int64(2), object(3)
memory usage: 37.0+ KB
None


In [36]:
# check the shape of the data
print(df_user.shape);

(943, 5)


The dataset has 943 rows and 5 columns

In [37]:
# describe the data
print(df_data.describe());

            user id       movie id         rating     timestamp
count  100000.00000  100000.000000  100000.000000  1.000000e+05
mean      462.48475     425.530130       3.529860  8.835289e+08
std       266.61442     330.798356       1.125674  5.343856e+06
min         1.00000       1.000000       1.000000  8.747247e+08
25%       254.00000     175.000000       3.000000  8.794487e+08
50%       447.00000     322.000000       4.000000  8.828269e+08
75%       682.00000     631.000000       4.000000  8.882600e+08
max       943.00000    1682.000000       5.000000  8.932866e+08


In [38]:
# check for missing data
def missing_check(df):
    total = df.isnull().sum().sort_values(ascending=False)   # total number of null values
    percent = (df.isnull().sum()/df.isnull().count()).sort_values(ascending=False)  # percentage of values that are null
    missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])  # putting the above two together
    return missing_data # return the dataframe
missing_check(df_user)

Total  Percent
zip code        0      0.0
occupation      0      0.0
gender          0      0.0
age             0      0.0
user id         0      0.0

The dataset has no missing values

#### 4. Find the number of movies per genre using the item data - 5 marks

In [ ]:
# use sum on the default axis

#### 5. Find the movies that have more than one genre - 2.5 marks

In [ ]:
#hint: use sum on the axis = 1

#### 6. Drop the movie where the genre is unknown - 2.5 marks

### 7. Univariate plots of columns: 'rating', 'Age', 'release year', 'Gender' and 'Occupation' - 10 marks

In [ ]:
# HINT: use distplot for age and countplot for gender,ratings,occupation.
# HINT: Please refer to the below snippet to understand how to get to release year from release date. You can use str.split()
# as depicted below
# Hint : Use displot without kde for release year or line plot showing year wise count.

In [1]:
a = 'My*cat*is*brown'
print(a.split('*')[3])

#similarly, the release year needs to be taken out from release date

#also you can simply slice existing string to get the desired data, if we want to take out the colour of the cat

print(a[10:])
print(a[-5:])

brown
brown
brown


In [ ]:
#your answers here

### 8. Visualize how popularity of genres has changed over the years - 10 marks

Note that you need to use the number of releases in a year as a parameter of popularity of a genre

Hint 

1: you need to reach to a data frame where the release year is the index and the genre is the column names (one cell shows the number of release in a year in one genre) or vice versa.
Once that is achieved, you can either use univariate plots or can use the heatmap to visualise all the changes over the years 
in one go. 

Hint 2: Use groupby on the relevant column and use sum() on the same to find out the nuumber of releases in a year/genre.  

In [ ]:
#Your answer here

### 9. Find the top 25 movies according to average ratings such that each movie has number of ratings more than 100 - 10 marks

Hint : 
1. First find the movies that have more than 100 ratings(use merge, groupby and count). Extract the movie titles in a list.
2. Find the average rating of all the movies and sort them in the descending order. You will have to use the .merge() function to reach to a data set through which you can get the names and the average rating.
3. Use isin(list obtained from 1) to filter out the movies which have more than 100 ratings.

Note: This question will need you to research about groupby and apply your findings. You can find more on groupby on https://realpython.com/pandas-groupby/.

In [ ]:
#your answer here

### 10. See gender distribution across different genres check for the validity of the below statements - 10 marks

* Men watch more drama than women
* Women watch more Sci-Fi than men
* Men watch more Romance than women


1. There is no need to conduct statistical tests around this. Just compare the percentages and comment on the validity of the above statements.

2. you might want ot use the .sum(), .div() function here.
3. Use number of ratings to validate the numbers. For example, if out of 4000 ratings received by women, 3000 are for drama, we will assume that 75% of the women watch drama.

#### Conclusion:

